# Generated by Django 5.2.1 on 2025-05-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='sheha',
            name='declaration',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_resides_in_shehia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sheha_knows_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
