# Generated by Django 5.2.1 on 2025-05-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
