# Generated by Django 5.2.1 on 2025-05-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0002_remove_applicant_declaration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_resides_in_shehia',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='declaration_accepted',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='sheha_knows_applicant',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='verified_at',
        ),
    ]
