# Generated by Django 5.2.1 on 2025-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0003_alter_applicant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheha',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
