# Generated by Django 5.2.1 on 2025-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0010_mockbankloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='bank_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_verified_by_sheha',
            field=models.BooleanField(default=False),
        ),
    ]
