# Generated by Django 5.2.1 on 2025-06-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0011_applicant_bank_status_applicant_bank_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
