# Generated by Django 5.2.1 on 2025-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0012_business_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheha',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
