# Generated by Django 5.2.1 on 2025-06-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0013_alter_sheha_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='bank_status',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='bank_verified',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_verified_by_sheha',
        ),
    ]
