# Generated by Django 5.2.1 on 2025-06-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0016_applicant_bank_status_applicant_bank_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockbankloan',
            old_name='bank_account_no',
            new_name='bank_no',
        ),
        migrations.RenameField(
            model_name='mockbankloan',
            old_name='has_loan',
            new_name='has_active_loan',
        ),
        migrations.AlterField(
            model_name='business',
            name='bank_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
