# Generated by Django 5.2.1 on 2025-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0017_rename_bank_account_no_mockbankloan_bank_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bank_no',
            field=models.CharField(max_length=20),
        ),
    ]
