# Generated by Django 5.2.1 on 2025-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0018_alter_business_bank_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockbankloan',
            name='bank_no',
            field=models.CharField(max_length=20),
        ),
    ]
