# Generated by Django 5.2.1 on 2025-06-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0019_alter_mockbankloan_bank_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bank_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mockbankloan',
            name='bank_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
