# Generated by Django 5.2.1 on 2025-06-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0020_alter_business_bank_no_alter_mockbankloan_bank_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='bank_verified',
            new_name='is_verified_by_bank',
        ),
        migrations.RemoveField(
            model_name='business',
            name='declaration_accepted',
        ),
        migrations.RemoveField(
            model_name='business',
            name='verification_status',
        ),
    ]
