# Generated by Django 5.2.1 on 2025-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0021_rename_bank_verified_applicant_is_verified_by_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
