# Generated by Django 5.2.1 on 2025-06-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0022_applicant_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockBankLoan',
        ),
    ]
