# Generated by Django 5.2.1 on 2025-06-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0024_alter_sheha_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('repayment_period', models.PositiveIntegerField()),
                ('business_overview', models.TextField()),
                ('market_analysis', models.TextField()),
                ('financial_info', models.TextField()),
                ('growth_strategy', models.TextField()),
                ('plan_attachment', models.FileField(blank=True, null=True, upload_to='plans/')),
                ('score', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('system_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empowerment_app.applicant')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empowerment_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='LoanExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='empowerment_app.loanapplication')),
            ],
        ),
    ]
