# Generated by Django 5.2.1 on 2025-06-27 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0026_loanofficer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
