# Generated by Django 5.2.1 on 2025-06-27 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0027_loanapplication_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
