# Generated by Django 5.2.1 on 2025-06-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0028_alter_loanofficer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('applicant', 'bank_no')},
        ),
    ]
