# Generated by Django 5.2.1 on 2025-06-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0029_alter_business_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bank_no',
            field=models.CharField(max_length=20),
        ),
    ]
