# Generated by Django 5.2.1 on 2025-07-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0031_loantype_remove_business_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='financial_info',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='market_analysis',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_customers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='new_customers_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='who_are_your_customers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
