# Generated by Django 5.2.1 on 2025-07-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0032_remove_loanapplication_financial_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='business_overview',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='growth_strategy',
        ),
    ]
