# Generated by Django 5.2.1 on 2025-07-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0034_business_latitude_business_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
    ]
