# Generated by Django 5.2.1 on 2025-07-29 08:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment_app', '0036_alter_business_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
