# Generated by Django 5.2.1 on 2025-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockBankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_no', models.CharField(max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('has_active_loan', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_status', models.CharField(default='N/A', max_length=20)),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
