# Generated by Django 5.2.1 on 2025-06-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockbankloan',
            name='bank_no',
            field=models.CharField(max_length=20),
        ),
    ]
